[DEFAULT]
# Configuración global por defecto para todos los medios
dpi = 250
calidad = 90
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3
rutabase = C:/Users/
base_lock = /Downloads/
# auto_scale = True  → descubre automáticamente la mejor escala antes de descargar.
#                      Reemplaza el tm configurado por la máxima resolución disponible.

[FTP]
# Configuración FTP común para todos los medios
host = 192.168.0.118
user = jaquebot
pass = SDmaw7YsyF7SYiSw



[Espectador]
# Configuración para el medio Espectador
impreso = Espectador
libro = ef58
token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYxNzQ5NjY2LCJhYiI6Ild1emkzaXJBdjBOMU8zSXYtaDI1RFFNa3hINkdmWENjYms0S2F0SGNqbmhMdmtpblFhU1FkRmpxcklscUJhWl9mNzYyazRPRTRfdElfNEFlckVJY1h3ISEiLCJhYyI6NjE3NDk2NjYsImFkIjoxLCJhZSI6MjA4NCwiYWYiOjEsImFpIjozNDE2LCJhaiI6MjE4NywiYWsiOi0yMzkxMTk5NzgsImFtIjoiZXMiLCJhbiI6ImVzLUVTIiwiYXAiOi0xMTY2NTczMzgyLCJleHAiOjE3NzkzMTg0MTksImlzcyI6InByIn0.1YmrxNwKA0jcMrgZ1KnAXta_xnIX6jD54GRnZ-BgWuQ
url_ids = 00000000001001,00000051001001
auto_scale = True
ftp_path = /Espectador
base02 = Downloads/Diarios_local/Espectador
lock_file = Espectador.lock
use_tokens = False
correcciones_json = Nextcloud/99_Multimedia/RTMP/Impresos/Pruebas/correciones.json

[Opinion]
# Configuración para el medio Opinion
impreso = Opinion
libro = ea57
token = j4b8W7kfh6-R4ONT0ksOuf-bB1eU-NvtQIp5mJ9UticxS6AhafQckq7p2QdYtobzNiAZkVQt9d448QWzwdlkgw!!
url_ids = 00000000001001,00000051001001
auto_scale = True
ftp_path = /Opinion
base02 = /Downloads/Diarios_local/Opinion/
lock_file = {impreso}.lock
use_tokens = False
correcciones_json = Nextcloud/99_Multimedia/RTMP/Impresos/Pruebas/correciones.json

[Publimetro]
# Configuración para el medio Publimetro
impreso = Publimetro
libro = 34nd
tokens = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYxNzQ5NjY2LCJhYiI6InZJTXdGVk5aUHh4MUd2cm1vLVlTSjBTRzdxcFhsdDRPSHM4cGZvNEhyTjJfMWdfVTZ3dzRmaEI3WHVncFowdW1yTlA0T3JQOVhkZWZRSGlFT1BUTklnISEiLCJhYyI6NjE3NDk2NjYsImFkIjoxLCJhZSI6MjA4NCwiYWYiOjEsImFpIjozNDE2LCJhaiI6MjE4NywiYWsiOi0yMzkxMTk5NzgsImFtIjoiZXMiLCJhbiI6ImVzLUVTIiwiYXAiOi0xMTY2NTczMzgyLCJleHAiOjE3NzkzMTg1NjgsImlzcyI6InByIn0.-iDtp69wU7nOqDKER7yvRRFdj0zjpexyFHlWZVx_wEs
url_ids = 00000000001001,00000052001001
auto_scale = True
ftp_path = /Publimetros
base02 = /Downloads/Diarios_local/Publimetro/
lock_file = 07_publimetro.lock
use_tokens = True
use_browser_auth = True


